"use client";
import { useState } from "react";
import Link from "next/link";

const sections = [
  {
    id: "overview",
    icon: "deployed_code",
    title: "Overview",
    content: [
      {
        heading: "What is ECO-3D?",
        body: `ECO-3D is an AI-powered sustainable land development platform that combines satellite imagery analysis, environmental data, and generative architecture to produce optimized floor plans and 3D building models. The platform is designed to maximize energy efficiency through intelligent solar and wind orientation.`
      },
      {
        heading: "Core Philosophy",
        body: `Every floor plan generated by ECO-3D is shaped by real environmental data — sun exposure hours, prevailing wind direction, flood risk, soil type, and tree density. The goal is to create buildings that use the wind for natural ventilation and the sun for natural brightness, reducing dependence on fans, tube-lights, and HVAC systems.`
      }
    ]
  },
  {
    id: "getting-started",
    icon: "play_arrow",
    title: "Getting Started",
    content: [
      {
        heading: "Step 1 — Select a Plot",
        body: `Navigate to the Map page. Use the interactive satellite map to click on any land plot. The system will detect the plot boundary and extract its GPS coordinates. You can zoom in to fine-tune the selection.`
      },
      {
        heading: "Step 2 — Run Analysis",
        body: `After selecting a plot, ECO-3D runs a 5-layer AI pipeline: satellite segmentation (DeepLabV3 + YOLOv8), environmental feature extraction (NDVI, DEM, rainfall), flood risk prediction (XGBoost), buildability scoring (MLP neural network), and floor plan optimization (genetic algorithm).`
      },
      {
        heading: "Step 3 — Configure Your Floor Plan",
        body: `On the Blueprint Generator page, set your plot shape (Rectangle, L-Shape, T-Shape, Irregular, Square), house type, number of bedrooms, bathrooms, and additional rooms like Puja Room, Garage, Office, or Dining Room. The system enforces realistic room count limits based on your plot area.`
      },
      {
        heading: "Step 4 — View the 3D Model",
        body: `Once a floor plan is generated, click "View 3D Model" to see a fully rendered three-dimensional building with real-time sun position, animated wind flow, furniture placement, and window/door openings.`
      }
    ]
  },
  {
    id: "plot-shapes",
    icon: "architecture",
    title: "Plot Shapes",
    content: [
      {
        heading: "Rectangle",
        body: `The most common plot shape. Width-to-depth ratio of approximately 1.4:0.72. Ideal for standard residential layouts with good north-south solar access.`
      },
      {
        heading: "Square",
        body: `Equal width and height. Excellent for compact designs. Best for plots under 150 m² where maximizing usable floor area is critical.`
      },
      {
        heading: "L-Shape",
        body: `An L-shaped plot (or L-shaped building footprint) is common in corner plots. ECO-3D renders the plot boundary as a true L polygon and places rooms to fit within it, with the longer wing typically hosting bedrooms and the shorter wing hosting service areas.`
      },
      {
        heading: "T-Shape",
        body: `A T-shaped plot has a wide bar at the top and a narrower stem. ECO-3D places public rooms (living, kitchen, dining) in the wide bar and private rooms (bedrooms, bathrooms) in the stem.`
      },
      {
        heading: "Irregular",
        body: `For non-standard plots, ECO-3D uses a 6-point irregular polygon approximation. Rooms are placed with a polygon containment check to ensure they fit within the plot boundary.`
      }
    ]
  },
  {
    id: "eco-optimization",
    icon: "eco",
    title: "Eco Optimization",
    content: [
      {
        heading: "Solar Gain Optimization",
        body: `When "Maximize Sunlight" is enabled, living rooms, bedrooms, offices, and puja rooms are assigned a sun-facing orientation based on the plot's latitude (south-facing in the northern hemisphere, north-facing in the southern hemisphere). Windows are placed on exterior walls facing the sun to allow maximum daylight penetration, reducing the need for artificial lighting.`
      },
      {
        heading: "Natural Ventilation",
        body: `When "Natural Ventilation" is enabled, kitchens, bathrooms, and utility rooms are oriented toward the prevailing wind direction fetched from real-time OpenWeatherMap data. This creates a cross-ventilation axis that allows fresh air to flow through the house without fans. Windows are placed on opposite walls to establish airflow paths.`
      },
      {
        heading: "Tree Preservation",
        body: `YOLOv8 detects trees in satellite imagery. When "Tree Preservation" is enabled, the floor plan footprint is shifted away from detected tree root zones. The count of preserved trees is shown in the Efficiency HUD.`
      },
      {
        heading: "Fitness Score",
        body: `The genetic algorithm produces a fitness score (0–100%) that combines solar gain, cross-ventilation efficiency, tree preservation, structural safety (slope), and flood safety. Higher scores mean more sustainable and livable designs.`
      }
    ]
  },
  {
    id: "room-guide",
    icon: "meeting_room",
    title: "Room Guide & Limits",
    content: [
      {
        heading: "Area-Based Room Limits",
        body: `ECO-3D enforces realistic room count limits based on your plot area:\n
• < 60 m²: 1 bed, 1 bath (studio/micro-home)
• 60–100 m²: 2 beds, 1 bath, optional puja room
• 100–150 m²: 3 beds, 2 baths, office, dining, utility, puja room
• 150–250 m²: 4 beds, 2 baths + garage, all optional rooms
• 250–400 m²: 5 beds, 3 baths, 2 offices, all rooms
• 400+ m²: 6 beds, 4 baths, 2 kitchens, 2 garages`
      },
      {
        heading: "Puja Room",
        body: `The puja room is placed in the northeast zone of the floor plan by default (Vastu-compliant). It is sized 2m × 2m to 3m × 3m and includes a sun-facing orientation.`
      },
      {
        heading: "Garage",
        body: `Garages are placed on the south-facing exterior wall with a wide door opening. They are sized 5m–7.5m × 4.5m–6m and marked with a car silhouette in both 2D and 3D views.`
      }
    ]
  },
  {
    id: "3d-model",
    icon: "view_in_ar",
    title: "3D Model",
    content: [
      {
        heading: "Real-Time Sun Position",
        body: `The 3D model sun position is calculated using the current time of day. The sun sphere moves across the sky based on the hour angle formula, reflecting how sunlight actually enters the building at the current moment. In the northern hemisphere, the sun rises in the east, reaches peak height in the south at noon, and sets in the west.`
      },
      {
        heading: "Enhanced Wind Animation",
        body: `Wind is visualized as animated particle streams flowing across the entire 3D model in the prevailing wind direction. Cone-shaped particles spawn from the windward edge, travel through the model, and fade out on the leeward side — simulating natural cross-ventilation flow.`
      },
      {
        heading: "Camera Modes",
        body: `Three camera modes are available: Isometric (45° overhead view), Top-Down (direct overhead for floor plan comparison), and Interior (first-person view at eye level for room walkthrough).`
      },
      {
        heading: "Export BIM",
        body: `The Export BIM button generates a JSON-format Building Information Model file with room dimensions, wall positions, window placements, and eco-scores. The file can be imported into BIM tools for further architectural development.`
      }
    ]
  },
  {
    id: "api",
    icon: "code",
    title: "API Reference",
    content: [
      {
        heading: "POST /analyze-plot",
        body: `Analyzes a plot at given coordinates.\n
Request body: { plot_id, lat, lon, polygon? }
Returns: segmentation, tree_coordinates, environmental, flood_probability, buildability_score`
      },
      {
        heading: "POST /generate-floorplan",
        body: `Generates an optimized floor plan.\n
Request body: { plot_id, plot_area_sqm, num_floors, plot_shape, house_type, room_preferences: { bedrooms, bathrooms, puja_room, garage, office, dining, utility }, maximize_sunlight, natural_ventilation, sustainability_priority, preserve_trees }
Returns: layout (rooms array), fitness_score, sunlight_score, ventilation_score, tree_preserved_count`
      },
      {
        heading: "GET /report/{plot_id}",
        body: `Returns a full analysis report for a plot including all environmental data, floor plan scores, and recommendations.`
      }
    ]
  }
];

export default function DocsPage() {
  const [activeSection, setActiveSection] = useState("overview");
  const current = sections.find(s => s.id === activeSection)!;

  return (
    <>
      <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
      <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" rel="stylesheet" />
      <div style={{ minHeight: "100vh", background: "#080e0e", fontFamily: "'Space Grotesk',sans-serif", color: "white" }}>

        {/* Header */}
        <header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 32px", background: "rgba(8,14,14,0.98)", borderBottom: "1px solid rgba(13,242,242,0.08)", position: "sticky", top: 0, zIndex: 50 }}>
          <Link href="/" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none" }}>
            <span className="material-symbols-outlined" style={{ color: "#0df2f2", fontSize: 24 }}>deployed_code</span>
            <div>
              <div style={{ color: "white", fontWeight: 700, fontSize: 16 }}>ECO-3D <span style={{ color: "rgba(13,242,242,0.5)", fontWeight: 300 }}>Docs</span></div>
              <div style={{ fontSize: 9, color: "#475569", textTransform: "uppercase", letterSpacing: "0.15em" }}>Documentation</div>
            </div>
          </Link>
          <nav style={{ display: "flex", gap: 24 }}>
            <Link href="/" style={{ color: "#64748b", fontSize: 12, textDecoration: "none", fontWeight: 500, textTransform: "uppercase", letterSpacing: "0.1em" }} className="hover:text-primary">Home</Link>
            <Link href="/map" style={{ color: "#0df2f2", fontSize: 12, textDecoration: "none", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.1em" }}>Launch App →</Link>
          </nav>
        </header>

        <div style={{ display: "flex", maxWidth: 1200, margin: "0 auto", padding: "48px 32px", gap: 48 }}>
          {/* Sidebar */}
          <aside style={{ width: 220, flexShrink: 0 }}>
            <div style={{ fontSize: 9, color: "rgba(13,242,242,0.4)", textTransform: "uppercase", letterSpacing: "0.18em", fontWeight: 700, marginBottom: 16 }}>Contents</div>
            {sections.map(s => (
              <button key={s.id} onClick={() => setActiveSection(s.id)}
                style={{
                  display: "flex", alignItems: "center", gap: 10, width: "100%", padding: "10px 14px",
                  marginBottom: 4, background: activeSection === s.id ? "rgba(13,242,242,0.08)" : "transparent",
                  border: `1px solid ${activeSection === s.id ? "rgba(13,242,242,0.2)" : "transparent"}`,
                  borderRadius: 8, cursor: "pointer", textAlign: "left",
                  color: activeSection === s.id ? "#0df2f2" : "#64748b",
                  fontSize: 12, fontWeight: activeSection === s.id ? 700 : 400,
                  fontFamily: "'Space Grotesk',sans-serif", transition: "all 0.2s"
                }}>
                <span className="material-symbols-outlined" style={{ fontSize: 14 }}>{s.icon}</span>
                {s.title}
              </button>
            ))}
          </aside>

          {/* Content */}
          <main style={{ flex: 1 }}>
            {/* Section header */}
            <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 32, paddingBottom: 24, borderBottom: "1px solid rgba(13,242,242,0.08)" }}>
              <div style={{ width: 44, height: 44, background: "rgba(13,242,242,0.08)", border: "1px solid rgba(13,242,242,0.15)", borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center" }}>
                <span className="material-symbols-outlined" style={{ color: "#0df2f2", fontSize: 22 }}>{current.icon}</span>
              </div>
              <div>
                <h1 style={{ fontSize: 28, fontWeight: 800, color: "white", margin: 0, lineHeight: 1.2 }}>{current.title}</h1>
                <p style={{ fontSize: 12, color: "#64748b", margin: 0, marginTop: 4 }}>ECO-3D Documentation</p>
              </div>
            </div>

            {/* Content items */}
            {current.content.map((item, i) => (
              <div key={i} style={{ marginBottom: 36 }}>
                <h2 style={{ fontSize: 16, fontWeight: 700, color: "#0df2f2", marginBottom: 12, display: "flex", alignItems: "center", gap: 8 }}>
                  <span style={{ color: "rgba(13,242,242,0.3)", fontSize: 11, fontFamily: "monospace" }}>{String(i+1).padStart(2,"0")}.</span>
                  {item.heading}
                </h2>
                <div style={{ background: "rgba(13,242,242,0.02)", border: "1px solid rgba(13,242,242,0.06)", borderRadius: 12, padding: "20px 24px" }}>
                  {item.body.split("\n").map((line, j) => (
                    <p key={j} style={{
                      color: line.startsWith("•") ? "#94a3b8" : "#cbd5e1",
                      fontSize: 14,
                      lineHeight: 1.8,
                      margin: line.startsWith("•") ? "4px 0" : "0 0 12px",
                      paddingLeft: line.startsWith("•") ? 8 : 0,
                      fontFamily: line.startsWith("{") || line.startsWith("POST") || line.startsWith("GET") ? "monospace" : "inherit",
                      fontSize: line.startsWith("{") || line.startsWith("POST") || line.startsWith("GET") ? 12 : 14,
                    }}>{line || ""}</p>
                  ))}
                </div>
              </div>
            ))}

            {/* Next section */}
            {sections.findIndex(s => s.id === activeSection) < sections.length - 1 && (
              <div style={{ marginTop: 48, paddingTop: 24, borderTop: "1px solid rgba(13,242,242,0.08)", display: "flex", justifyContent: "flex-end" }}>
                <button
                  onClick={() => setActiveSection(sections[sections.findIndex(s => s.id === activeSection) + 1].id)}
                  style={{ display: "flex", alignItems: "center", gap: 8, padding: "10px 20px", background: "rgba(13,242,242,0.06)", border: "1px solid rgba(13,242,242,0.15)", borderRadius: 8, color: "#0df2f2", fontSize: 12, cursor: "pointer", fontFamily: "'Space Grotesk',sans-serif", fontWeight: 700 }}>
                  Next: {sections[sections.findIndex(s => s.id === activeSection) + 1].title}
                  <span className="material-symbols-outlined" style={{ fontSize: 14 }}>arrow_forward</span>
                </button>
              </div>
            )}
          </main>
        </div>
      </div>
    </>
  );
}
